version: '3'

services:
   web:
      build: 
         context: './image_www'
      container_name: 'ctf_sqli_web_diff'
      tty: 'true'
      restart: 'on-failure'
      networks:
         net-10.10.0.0:
            ipv4_address: '10.10.0.2'
      ports:
         - '60080:80/tcp'
         - '60443:443/tcp'
   mysql:
      build: './image_mysql'
      container_name: 'ctf_sqli_mysql_diff'
      tty: 'true'
      restart: 'on-failure'
      networks:
         net-10.10.0.0:
            ipv4_address: '10.10.0.3'

networks:
  net-10.10.0.0:
      name: 'net-10.10.0.0'
      ipam:
         config:
            - subnet: '10.10.0.0/24'
