version: "3"

services:
    iot:
        build: ./image_flask
        image: seed-image-flask
        container_name: iot-192.168.60.80
        tty: true
        cap_add:
                - ALL
        volumes:
                - ./volumes/rebind_iot:/app/rebind_iot
        networks:
            net-192.168.60.0:
                ipv4_address: 192.168.60.80
        command: bash -c "
                  FLASK_APP=/app/rebind_iot flask run --host 0.0.0.0 --port 80
                 "

    Router:
        build: ./image_ubuntu
        image: router
        container_name: router
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1
        networks:
            net-192.168.60.0:
                ipv4_address: 192.168.60.11
            net-10.9.0.0:
                ipv4_address: 10.9.0.11
        command: bash -c "
                      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
                      iptables -A FORWARD -d 192.168.60.80 -j DROP  &&
                      /start.sh
                 "

    ns-attacker:
        build: ./image_ns_attacker
        image: ns-attacker
        container_name: ns-attacker-10.9.0.153
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.153

    www-attacker:
        image: seed-image-flask
        container_name: www-attacker-10.9.0.180
        tty: true
        cap_add:
                - ALL
        volumes:
                - ./volumes/rebind_server:/app/rebind_server
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.180
        command: bash -c "
                  FLASK_APP=/app/rebind_server flask run --host 0.0.0.0 --port 80
                 "

    local-server:
        build: ./image_local_server
        image: local-dns-server
        container_name: local-dns-server
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.53

networks:
    net-192.168.60.0:
        name: net-192.168.60.0
        ipam:
            config:
                - subnet: 192.168.60.0/24
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

