version: "3"

services:
    #### Base Image ###########################################################
    # This container image serves as the base for other image(s) in this setup,
    # but the container itself plays no role, and it will exit.
    base-apache-php:
        build: ./base-apache-php
        image: base-apache-php
        container_name: base-apache-php
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.199
    ###########################################################################

    www:
        build: ./image_www
        image: seed-image-www-sqli
        container_name: www-10.9.0.5
        tty: true
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5

    mysql:
        build: ./image_mysql
        image: seed-image-mysql-sqli
        container_name: mysql-10.9.0.6
        command: --default-authentication-plugin=mysql_native_password
        tty: true
        restart: always
        cap_add:
                - SYS_NICE  # CAP_SYS_NICE (surprise an error message)
        volumes:
                - ./mysql_data:/var/lib/mysql
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

