version: "3"

services:
    attacker:
        build: ./image_scapy
        image: seed-image-scapy
        container_name: seed-attacker
        tty: true
        cap_add:
                - ALL
        privileged: true
        volumes:
                - ./volumes:/volumes
        network_mode: host

    x-terminal:
        build: ./image_ubuntu_mitnick
        image: seed-image-ubuntu-mitnick
        container_name: x-terminal-10.9.0.5
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5

        command: bash -c "
                      /etc/init.d/openbsd-inetd start  &&
                      /start.sh
                 "
                  
    trusted-server:
        image: seed-image-ubuntu-mitnick
        container_name: trusted-server-10.9.0.6
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

