version: "3"

services:
   easy_server:
      build: 
         context: ./src/server
         args:
            DIFFICULTY: easy
            BUFFER_SIZE: 100
            FLAG_IN_MEM: "CHANGE_ME_EASY" # space characters not permitted!
      container_name: ctf_format_string_easy_server
      tty: true
      ports:
         - "1111:9999"
      restart: on-failure

   hard_server:
      build: 
         context: ./src/server
         args:
            DIFFICULTY: hard
            BUFFER_SIZE: 100
      container_name: ctf_format_string_hard_server
      tty: true
      ports:
         - "2222:9999"
      restart: on-failure
      
