version: "3"

services:
    elgg:
        build: ./image_www
        image: seed-image-www
        container_name: elgg-10.9.0.5
        tty: true
        ports:
          - 80:80
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5

    mysql:
        build: ./image_mysql
        image: seed-image-mysql
        container_name: mysql-10.9.0.6
        command: --default-authentication-plugin=mysql_native_password
        tty: true
        restart: always
        cap_add:
                - SYS_NICE  # CAP_SYS_NICE (supress an error message)
        volumes:
                - ./mysql_data:/var/lib/mysql
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

