version: "3"

services:
    hostA:
        build: ./Hosts
        image: seed-image-ubuntu-hosts
        container_name: A-10.8.0.99
        tty: true
        cap_add:
                - ALL
        devices:
                - "/dev/net/tun:/dev/net/tun"
        sysctls:
                - net.ipv4.ip_forward=1

        networks:
            net-10.8.0.0:
                ipv4_address: 10.8.0.99
        command: bash -c "
                      ip route add 192.168.20.0/24 via 10.8.0.11 &&
                      /etc/init.d/openbsd-inetd start  &&
                      service ssh start  &&
                      tail -f /dev/null
                 "

    hostA1:
        image: seed-image-ubuntu-hosts
        container_name: A1-10.8.0.5
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.8.0.0:
                ipv4_address: 10.8.0.5
        command: bash -c "
                      ip route add 192.168.20.0/24 via 10.8.0.11 &&
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

    hostA2:
        image: seed-image-ubuntu-hosts
        container_name: A2-10.8.0.6
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.8.0.0:
                ipv4_address: 10.8.0.6
        command: bash -c "
                      ip route add 192.168.20.0/24 via 10.8.0.11 &&
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

    hostB:
        image: seed-image-ubuntu-hosts
        container_name: B-192.168.20.99
        tty: true
        cap_add:
                - ALL
        devices:
                - "/dev/net/tun:/dev/net/tun"
        sysctls:
                - net.ipv4.ip_forward=1

        networks:
            net-192.168.20.0:
                ipv4_address: 192.168.20.99
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 192.168.20.11  &&
                      /etc/init.d/openbsd-inetd start  &&
                      service ssh start  &&
                      tail -f /dev/null
                 "
                  
    hostB1:
        image: seed-image-ubuntu-hosts
        container_name: B1-192.168.20.5
        tty: true
        cap_add:
                - ALL
        networks:
            net-192.168.20.0:
                ipv4_address: 192.168.20.5
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 192.168.20.11  &&
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

    hostB2:
        image: seed-image-ubuntu-hosts
        container_name: B2-192.168.20.6
        tty: true
        cap_add:
                - ALL
        networks:
            net-192.168.20.0:
                ipv4_address: 192.168.20.6
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 192.168.20.11  &&
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

    Router:
        image: handsonsecurity/seed-ubuntu:large-arm
        container_name: router-firewall
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1

        networks:
            net-10.8.0.0:
                ipv4_address: 10.8.0.11
            net-192.168.20.0:
                ipv4_address: 192.168.20.11
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.8.0.1 &&
                      iptables -t nat -A POSTROUTING ! -d 10.8.0.0/24 -j MASQUERADE -o eth0 &&
                      iptables -A FORWARD -i eth0 -p tcp -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT && 
                      iptables -A FORWARD -i eth0 -p tcp --dport 22 -j ACCEPT && 
                      iptables -A FORWARD -i eth0 -p tcp -j DROP && 
                      iptables -A FORWARD -i eth1 -d 93.184.216.0/24 -j DROP &&
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

networks:
    net-192.168.20.0:
        name: net-192.168.20.0
        ipam:
            config:
                - subnet: 192.168.20.0/24

    net-10.8.0.0:
        name: net-10.8.0.0
        ipam:
            config:
                - subnet: 10.8.0.0/24

